@domain = http://localhost:3000

### 
# 로그인
POST {{domain}}/auth/login
Content-Type: application/JSON

{
  "email": "test2@test.com",
  "password": "1234"
}

###
# 로그아웃
POST {{domain}}/auth/logout
Content-Type: application/JSON
