@domain = http://localhost:3000

### ----- 회원 1명
###
# 회원 가입
# role : 0(admin), 1(user), 2(seller)
POST {{domain}}/user/signup
Content-Type: application/JSON

{
  "email": "test2@test.com",
  "password": "1234",
  "passwordConfirm": "1234",
  "nickname": "test2",
  "role": 0
}

###
# 내 정보 조회
GET {{domain}}/user

###
# 내 정보 수정
PATCH {{domain}}/user
Content-Type: application/JSON

{
  "nickname": "test11"
}

###
# 회원 탈퇴
DELETE {{domain}}/user

### ----- 회원 목록
###
# 회원 목록 조회
GET {{domain}}/user/list

###
# 회원 목록 검색
# 검색 조건 : role, nickname, email
GET {{domain}}/user/list/nickname/0

### 
# 로그인
POST {{domain}}/user/login
Content-Type: application/JSON

{
  "email": "test2@test.com",
  "password": "1234"
}

###
# 로그아웃
POST {{domain}}/user/logout
Content-Type: application/JSON

###
# FAQ 작성
POST {{domain}}/faq
Content-Type: application/json

{
  "title": "고향사랑 기부금제도는 왜 만들어진 것인가요?",
  "content": "건전한 기부문화를 조성하고 지역경제를 활성화하려는 취지로 제정된 것입니다."
}

###
# FAQ 조회
GET {{domain}}/faq
Content-Type: application/json

###
# 특정 FAQ 조회
GET {{domain}}/faq/6
Content-Type: application/json

###
# FAQ 수정
PATCH {{domain}}/faq/6
Content-Type: application/json

{
  "title": "배송은 얼마나 걸리나요?",
  "content": "배송은 평균 2~3일 정도 소요되는 점 참고 부탁드립니다."
}

###
# FAQ 삭제
DELETE {{domain}}/faq/5
Content-Type: application/json
