@domain = http://localhost:3000

### 
# 찜 상품 등록
POST {{domain}}/wish
Content-Type: application/JSON

{
  "product_id" : 4
}

###
# 내가 찜한 상품 조회
GET {{domain}}/wish

###
# 상품 별 찜 조회 (productId)
GET {{domain}}/wish/5

###
# 찜 삭제 
DELETE {{domain}}/wish/6

###디코
POST https://discord.com/api/webhooks/1201904733498114058/cmcDp6O6t3AP_t3Lr3mH-3HYbHquc9NB1eiHtS-D2I-n1dj-FxBUoCKCTL-YoWwF8dAE
Content-Type: application/JSON

{
  "content": "이제 오류생길때마다 디코 메시지 가능",
  "tts": false,
  "embeds": [{
    "title": "이제 오류생길때마다 디코 메시지 가능",
    "description": "홀홀"
  }]
}